using System;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Input;
using System.Windows.Media.Animation;

namespace DPaste
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        private readonly Storyboard Sb = new Storyboard();
        private IEasingFunction Smooth { get; set; } = new QuadraticEase {
            EasingMode = EasingMode.EaseInOut
        }; 
        public MainWindow()
        {
            InitializeComponent();
        }

        private void Border_MouseLeftButtonDown(object sender, MouseButtonEventArgs e)
        {
            DragMove();
        }

        private async void DPaste_Loaded(object sender, RoutedEventArgs e)
        {
            await Task.Delay(1500);
            MainIcon.Visibility = Visibility.Collapsed;
            DPMainX.Visibility = Visibility.Visible;
        }

        private void ExitB_Click(object sender, RoutedEventArgs e) => Application.Current.Shutdown();

        private void MinimizeB_Click(object sender, RoutedEventArgs e) => WindowState = WindowState.Minimized;

        async private void Progress_Click(object sender, RoutedEventArgs e)
        {
            if (Input.Text.Replace(" ", "").Length == 0) {
                PGD.Content = "You must fill out the text box!";
                return;
            }
            Progress.IsEnabled = false;
            Progress.Content = "...";
            try
            {
                string cnt = Input.Text;
                StringBuilder builder = new StringBuilder();
                for (int i = 0; i < cnt.Length; i += 32766)
                {
                    int ccs = Math.Min(32766, cnt.Length - i);
                    string cca = cnt.Substring(i, ccs);
                    builder.Append(cca);
                }
                using (var wc = new HttpClient())
                {
                    wc.DefaultRequestHeaders.Add("User-Agent", "FlameIgniterDPasteTool");
                    var x1 = new MultipartFormDataContent
                    {
                        { new StringContent(builder.ToString(), Encoding.UTF8, "application/x-www-form-urlencoded"), "content" },
                        { new StringContent("Automatically Generated by DPaste Tool For Windows by FlameIgniter"), "title" }
                    };
                    HttpResponseMessage res = await wc.PostAsync("https://dpaste.com/api/", x1);
                    var res2 = await res.Content.ReadAsStringAsync();
                    if (res2.StartsWith("https://dpaste.com/"))
                    {
                        PGD.Content = "Uploaded successfully! Link copied to clipboard";
                        Clipboard.SetText(res2);
                    }
                    else throw new Exception("Unknown Response: " + res2);
                }
            }
            catch (Exception ex) {
                PGD.Content = "Error: " + ex.ToString();
            }
            ThicknessAnimation Animation = new ThicknessAnimation()
            {
                From = new Thickness(15, 0, 0, 15),
                To = new Thickness(15, 0, 0, 25),
                Duration = new Duration(TimeSpan.FromMilliseconds(150)),
                AutoReverse = true
            };
            Storyboard.SetTarget(Animation, PGD);
            Storyboard.SetTargetProperty(Animation, new PropertyPath(MarginProperty));
            Sb.Children.Add(Animation);
            Sb.Begin();
            Sb.Children.Remove(Animation);
            Progress.IsEnabled = true;
            Progress.Content = "Upload";
        }
    }
}
